name:  Test run on Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies and Run unit test suit
        run: npm install && npm test